/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package phasmo.java_phasmo_db;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import javax.swing.JOptionPane;


/**
 *
 * @author belpg
 */
public class mainFrame extends javax.swing.JFrame{   

    class GhostData{        
        String evi1;
        String evi2;
        String evi3;                
    
        public GhostData( String evi1, String evi2, String evi3){            
            this.evi1 = evi1;
            this.evi2 = evi2;
            this.evi3 = evi3;                                 
        }
    }
    
    public static boolean compareEvidences(List<String> list1, List<String> list2){
        HashSet<String> set1 = new HashSet<>();
        HashSet<String> set2 = new HashSet<>();
        
        for(String item : list1){
            String[] evidences = item.split(",");
            for(String evidence : evidences){
                set1.add(evidence.trim());
            }
        }
        
        for(String item : list2){
            String[] evidences = item.split(", ");
            for(String evidence : evidences){
                set2.add(evidence.trim());
            }
        }
        
        return set1.equals(set2);
    }
    
    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        listEv3 = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listEv1 = new javax.swing.JList<>();
        lblGhost = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listEv2 = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        lblHunt = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblStep = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblComp = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listEv3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "EMF5", "UV", "Spirit Box", "Orb", "Escrita", "Dots", "Temp" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(listEv3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 96, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Evidencia");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 58, 68, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Evidencia");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 58, 68, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Ghost:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Evidencia");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 58, 68, -1));

        listEv1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "EMF5", "UV", "Spirit Box", "Orb", "Escrita", "Dots", "Temp" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listEv1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 96, -1, -1));

        lblGhost.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblGhost.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(lblGhost, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 172, 25));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("discover the ghost with evidences");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 15, 331, -1));

        btn1.setText("Ghost Type");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 286, 136, 35));

        listEv2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "EMF5", "UV", "Spirit Box", "Orb", "Escrita", "Dots", "Temp" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listEv2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 96, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Passos");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 174, -1));

        lblHunt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(lblHunt, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 93, 18));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Sanidade");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 174, -1));

        lblStep.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(lblStep, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 93, 18));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Comportamento");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, -1, -1));
        getContentPane().add(lblComp, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 260, 110));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        ArrayList<GhostData> ghostList = new ArrayList<>();             
        ArrayList listTest = new ArrayList();        
        String ghostEvi1, ghostEvi2, ghostEvi3;
        ghostEvi1 = listEv1.getSelectedValue();
        ghostEvi2 = listEv2.getSelectedValue();
        ghostEvi3 = listEv3.getSelectedValue();
        ArrayList listEvidences = new ArrayList();
        listEvidences.add(ghostEvi1 + ", " + ghostEvi2 + ", " + ghostEvi3);
        listEvidences.toString();        
        /*
        String evi1, evi2, evi3, ghostName;
        */

        int ghostId = 0;              
        
        String url = "jdbc:mysql://localhost:3306/ghosts";
        String user = "phasmo_user";
        String password = "123456";               
        
        Connection conexao = null;               
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conexao = DriverManager.getConnection(url, user, password);
            ResultSet rsResults = conexao.createStatement().executeQuery("select * from ghost");
            while(rsResults.next()){
                /*                                
                    System.out.println("Id: " + rsResults.getInt("id"));              
                    System.out.println("Nome: " + rsResults.getString("ghost_name"));
                    ghostId = rsResults.getInt("id");

                    System.out.println("Evidences: " + rsResults.getString("first_evidence")
                            + ", " + rsResults.getString("second_evidence") + ", "
                            + rsResults.getString("last_evidence")
                    );    

                    System.out.println("Evidences Player:");
                    System.out.println("E1: " + ghostEvi1);
                    System.out.println("E2: " + ghostEvi2);
                    System.out.println("E3: " + ghostEvi3);
                */
                
                String ghostName = rsResults.getString("ghost_name");
                String evi1 = rsResults.getString("first_evidence");
                String evi2 = rsResults.getString("second_evidence");
                String evi3 = rsResults.getString("last_evidence");                
                
                ghostList.add(new GhostData(evi1 + ", ", evi2 + ", ", evi3));                 
                listTest.add(evi1 + ", " + evi2 + ", " + evi3);                                                
                
                if(compareEvidences(listTest, listEvidences)){                    
                    lblGhost.setText(ghostName);
                    lblStep.setText(rsResults.getString("step"));
                    lblHunt.setText(rsResults.getString("hunt_sanity"));
                    lblComp.setText("<html>" + rsResults.getString("comportament") + "</html>");
                    break;
                } else{
                    System.out.println("Error");
                    System.out.println("");                    
                }                
                System.out.println(listTest);                
                listTest.clear();                                
            }
        } catch (ClassNotFoundException ex) {
            System.out.println("Error " + ex.getMessage());
        } catch (SQLException ex){
            System.out.println("Error for access DataBase " + ex.getMessage());
        }
        finally{
            try{
                if(conexao != null){
                    conexao.close();
                }
            } catch (SQLException ex){
                JOptionPane.showMessageDialog(this, "Error closing connection: " + ex.getMessage());
            }

        }              
    }//GEN-LAST:event_btn1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){            
    
      
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }           

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblComp;
    private javax.swing.JLabel lblGhost;
    private javax.swing.JLabel lblHunt;
    private javax.swing.JLabel lblStep;
    private javax.swing.JList<String> listEv1;
    private javax.swing.JList<String> listEv2;
    private javax.swing.JList<String> listEv3;
    // End of variables declaration//GEN-END:variables
}
